# Generated by Django 5.0.7 on 2024-07-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agendamento',
            new_name='Agendamentos',
        ),
    ]
