# Generated by Django 5.0.7 on 2024-07-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_rename_agendamento_agendamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentos',
            options={'verbose_name': 'Agendamento'},
        ),
    ]
