# Generated by Django 5.0.7 on 2024-07-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamentos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Laboratório',
            },
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.laboratorios'),
        ),
    ]
