# Generated by Django 5.0.7 on 2024-07-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_professor_alter_agendamentos_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Professores',
        ),
        migrations.AlterModelOptions(
            name='professores',
            options={'verbose_name': 'Professore'},
        ),
    ]
