# Generated by Django 5.0.7 on 2024-09-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_imagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name': 'Agendamento'},
        ),
    ]
